Get current workers from Heroku
the-grid/guv pull request #193
Opened 2017-02-21 17:06 UTC by jonnor

Previously we'd *assume* that the number current workers is what it was last changed to by guv, as stored in the history. This is not generally right. For instance when we first start, we don't have such a value, and we won't have it until we make a scaling decision. Furthermore it is possible for other things than guv to go on change something, so even after having made a scaling decision we can go out of sync.
The canonical answer can be had by asking Heroku via the API. This doubles the number of requests we make per app. Which is normally not a problem, but for accounts which manage many apps this may cause to go over quota (since API quotas are per account).

2017-02-21 17:07 UTC, bergie commented on package.json
> +    "bluebird": "^3.4.7",
Async _and_ Bluebird? Might make sense to go all promises down the line

2017-02-21 17:08 UTC, bergie requested changes
Can we have some tests with mocked Heroku API?

2017-02-21 18:09 UTC, jonnor commented
@bergie we have end-to-end tests against the real Heroku API

2017-02-21 18:10 UTC, jonnor commented on package.json
> +    "bluebird": "^3.4.7",
Yes, it shall be all Promises over time. async should not be used in new code.

2017-02-21 20:45 UTC, jonnor commented
@bergie the tests were failing (for good reasons), and the bugs found have been fixed. The tests which have been modified to include calls to `mocks.Heroku.setCurrentWorkers` illustrate the current coverage of the functionality touched here.

2017-02-22 09:29 UTC, bergie approved these changes

2017-02-22 10:43 UTC, merged